### ISSUE TITLE
CONFIG_PATH: command not found

### ISSUE THREAD

**Issue by flytomatolll** [IMNearth/Curriculum-Learning-For-VLN#1]
Excuse me.I'll follow your order and the result is like this. How can I solve it.

xxx@LAPTOP-KT4CNMRD:~/Matterport3DSimulator$ CONFIG_PATH = /tasks/R2R-judy/configs
CONFIG_PATH: command not found

**Comment by IMNearth** [comment]
The first two lines of code is to tell you how to write CONFIG_PATH variable and CL_MODE variable, you should use the following command to start training.

```
python tasks/R2R-judy/main.py \
--config-file "path-to-config-file" \
TRAIN.DEVICE your_device_id \
TRAIN.CLMODE  "your_cl_mode"
```

**Comment by flytomatolll** [comment]
Thank you. I'll try again.

**Comment by 929343413** [comment]
My project directory is as follows：
![image](https://user-images.githubusercontent.com/54609709/160525442-c9e90def-0b34-4d8c-bd86-39ef1ebbc7fb.png)
So should my path be set like this？
CONFIG_PATH="/root/Matterport3DSimulator/tasks/configs"

Is the CL_MODE the same as yours?
and the your_device_id in command, how to check my device id?

I'm so sorry to trouble you
