### ISSUE TITLE
'MatterSim.Simulator' object has no attribute 'init'

### ISSUE THREAD

**Issue by flytomatolll** [IMNearth/Curriculum-Learning-For-VLN#2]
I'm sorry to bother you.When I run the script :

> 'python tasks/R2R-judy/main.py \
> --config-file tasks/R2R-judy/configs/follower/follower_config.yaml \
> TRAIN.DEVICE 0'

there is an error of "MatterSim.Simulator' object has no attribute 'init'". I don't know whether you have an idea about it or not.
And I try to use 'sim.initialize()' to replace 'sim.init()', and it seems that there is no error, but I don't know if there will be other errors in the future.And then I get this error:

> Traceback (most recent call last):
>   File "tasks/R2R-judy/main.py", line 125, in main
>     trainer.train(cfg, agent, cfg.OUTPUT.TSBOARD_DIR, train_env, valid_env)
>   File "/home/xxx/Matterport3DSimulator/tasks/R2R-judy/src/engine/__init__.py", line 12, in train
>     return train_follower(cfg, agent, tsboard_dir, train_env, valid_env, **kwargs)
>   File "/home/xxx/Matterport3DSimulator/tasks/R2R-judy/src/engine/trainer.py", line 106, in train_follower
>     agent.rollout(train_ml=True, feedback=cfg.AGENT.FEEDBACK)
>   File "/home/xxx/Matterport3DSimulator/tasks/R2R-judy/src/agent/follower.py", line 78, in rollout
>     obs = self.env.reset(restart=restart) if reset else self.env.observe()
>   File "/home/xxx/Matterport3DSimulator/tasks/R2R-judy/src/environ/common_env.py", line 349, in reset
>     self.env.newEpisodes(scanIds, viewpointIds, headings)
>   File "/home/xxx/Matterport3DSimulator/tasks/R2R-judy/src/environ/common_env.py", line 71, in newEpisodes
>     self.sims[i].newEpisode(scanId, viewpointId, heading)
> TypeError: newEpisode(): incompatible function arguments. The following argument types are supported:
>     1. (self: MatterSim.Simulator, arg0: List[str], arg1: List[str], arg2: List[float], arg3: List[float]) -> None
> 
> Invoked with: <MatterSim.Simulator object at 0x7f22c1322e68>, '2n8kARJN3HM', '3611ca6eb11f4a32a7cd3c073862860d', 4.062

Do you know how to solve it？Looking forward to your reply. Thanks.

**Comment by IMNearth** [comment]
Hi, I think the error comes from the incompatible version of M3D simulator. This repo is built on v0.1. 
Besides, the `init()` function used in my code is about a self-defined api in `utils/misc.py`. 
Please check the simulator version and the mentioned file. Hope this can help you.
